### PR TITLE
Added GKD350H support

### PR DESCRIPTION
**Pull request by mwilkens**
the GCW0 build couldn't initialize SDL on the GKD350H, this sets the video mode properly and offsets the screen to the middle of the 350H.

Tested and works, will probably work on the RG-350 and playgo as well :)

### CODE REVIEW

**Comment by gameblabla** [comment]
Why not just fix the GCW0 port code instead of making a separate one ? It seems that the only issue is that using triple buffering with hw surface could make it crash on the GKD350H.

**Comment by mwilkens** [comment]
Oh true, I can merge my changes into the GCW0 folder. Mostly just worried about the offsetting I am doing to the screen blit since it's a different resolution. The 350h didn't like a resolution that wasn't 320x240 but I don't have a GCW0 to test.

**Comment by gameblabla** [comment]
Oh actually nevermind, let's keep it that way. GCW0/RG-350 supports IPU while this doesn't. It's not using it right now but i want to use it in the future so go ahead and i'll merge it once you feel you are ready with the fixes.

**Comment by gameblabla** [comment]
Well i think that it should be good so i'll merge this. Thanks !

**Pull request merged**
